languageCode: "en-us"
baseUrl: "https://golang.wtf"
title: "wtf go"
theme: "anubis"
paginate: 10
enableRobotsTXT: true
permalinks:
  post: /:year/:month/:title/

#menu:
#  main:
#  - identifier: archive
#    name: Archive
#    title: Archive
#    url: /posts/
#    weight: 1
#  - identifier: about
#    name: About
#    title: About
#    url: /about/
#    weight: 0

params:
  author: "Sean Smith"
  description: "Sometimes go is f@#king hard"
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: auto
  readMore: true
  disableSummary: false
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  social:
  - id: twitter
    name: wwsean08
    url: "https://twitter.com/wwsean08"
#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"
