name: pull request

on:
  pull_request:

jobs:
  validate-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --path-warnings --i18n-warnings

  validate-author:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Check that author bio exists
        run: |
          files=$(ls content/posts)
          for file in $files; do
            authorLine=$(grep -e "^author" content/posts/$file)
            author=$(echo $authorLine | cut -d " " -f 2 | tr -d "\"")
            if [ ! -f "data/authors/$author.yaml" ]; then
              echo "$file has an author that does not include a bio, please place one under data/authors"
              exit 1
            fi
          done

  validate-not-draft:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Check that draft is set to false
        run: |
          files=$(ls content/posts)
          for file in $files; do
            draftLine=$(grep -e "^draft" content/posts/$file)
            draftStatus=$(echo $draftLine | cut -d " " -f 2)
            echo $draftStatus | grep -i -q "false"
            draftIsFalse=$?
            if [ $draftIsFalse -ne 0 ]; then
              echo "$file is still a draft, please mark it ready for publishing by setting draft to false"
              exit 1
            fi
          done
